In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt

columns = ["target", "id", "date", "flag", "user", "text"]

df = pd.read_csv("training.1600000.processed.noemoticon.csv",encoding="latin-1",names=columns)

df = df[["target","text"]]
df.head()

   target                                               text
0       0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1       0  is upset that he can't update his Facebook by ...
2       0  @Kenichan I dived many times for the ball. Man...
3       0    my whole body feels itchy and like its on fire
4       0  @nationwideclass no, it's not behaving at all....

In [ ]:
negative = df[df["target"]==0].sample(n=100000, random_state = 42)
positive = df[df["target"]==4].sample(n=100000,random_state=42)

data = pd.concat([positive,negative])
data = data.sample(frac=1,random_state=42).reset_index(drop=True) # suffle the order frac 1 means 100% of the data. reset_index(drop=true) resets the indexes 

data["target"] = data["target"].map({0:0,4:1})
data.head()

   target                                               text
0       1  Looks like the sun finally located Trondheim ;...
1       0  A long weekend begins. The sun is shining and ...
2       1         to the beach we go! hope it stays nice...
3       0  @JBFutureboy I missed it  busted need to do a ...
4       0          Why I can't change my background image??

In [ ]:
counts = data["target"].value_counts()

plt.bar(['positive','negative'],counts.values,colour=["red","green"])
plt.title("Class Distribution in sample")
plt.ytitle("Number of tweets")

plt.show()